### PR TITLE
Added russian language

### PR DESCRIPTION
**Pull request by IgoR-NiK**
Added russian language

### CODE REVIEW

**Comment by ZsharE** [comment]
Please provide a stack trace in russian language so i could test it.

Thanks

**Comment by IgoR-NiK** [comment]
```cs
System.ApplicationException: Ошибка в ходе выполнения
 ---> System.FormatException: Входная строка имела неверный формат.
   в System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   в System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   в System.Int32.Parse(String s)
   в MyNamespace.IntParser.Execute(String s) в C:\apps\MyNamespace\IntParser.cs:строка 13
   --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в MyNamespace.IntParser.Execute(String s) в C:\apps\MyNamespace\IntParser.cs:строка 17
   в MyNamespace.Program.Main(String[] args) в C:\apps\MyNamespace\Program.cs:строка 13
```

**Comment by ZsharE** [comment]
Hi @IgoR-NiK ,

First, thanks for providing us a stack trace in russian language.

I tested the code from your pull request and I found some problems on the pretty print functionality.
I made a demo on jsfiddle: https://jsfiddle.net/ZsharE/zgutcs8m/

I pointed with arrows where the issues are:
pretty-print-netStack-russian-language

Seems like this regex has some problems:
```javascript
new RegExp(`(\\s*?)${at_language} (.*?)\\((.*?)\\)`, 'g')
```

The problem here is that the `at` and `in` words are the same in russian language: `в`.
I tried to fix this but, unfortunately, i couldn't came up with a solution.

Do you have any ideas ?
Thanks

**Comment by IgoR-NiK** [comment]
Hi @ZsharE 

Thanks for testing the code from my pull request.
I have corrected in the last commit

**Comment by ZsharE** [comment]
Thanks, much appreciated!

I updated the code in the [staging branch](https://github.com/elmahio/netStack.js/tree/staging), after some tests i'll put it into production.

**Comment by ThomasArdal** [comment]
@IgoR-NiK Just a quick update on this. A new netStack.js version 1.1.0 has been published to [npm](https://www.npmjs.com/package/netstack.js/v/1.1.0) and on [GitHub](https://github.com/elmahio/netStack.js/releases/tag/1.1.0). Thank you again for your contribution.

**Pull request closed without merging**
